#!/bin/bash
source $(dirname $0)/../../util/helpers.sh

# Request apt-params.sh to generate the list of nodes so that we can kill.
# The list can be in any order.
#
# Do not overwrite the nodemap previously generated by run-all.sh
apt_gen_nodes=1
overwrite_nodemap=0
source $(dirname $0)/apt-params.sh

for i in $apt_nodes; do
	blue "Killing node $i"
	ssh -oStrictHostKeyChecking=no akalianode-$i\.RDMA.fawn.apt.emulab.net \
		"cd hots/app/$apt_app/; ./kill.sh" &
done

wait
